### ISSUE TITLE
Unknown protocol

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vbartacek/aacdecoder-android#54]
```

1) Play http://wma01.fluidstream.net:8240/

2) java.net.MalformedURLException: Unknown protocol: icy

04-27 19:54:36.005    6204-6728/it.radio W/AACPlayer﹕ No response code for 
url http://wma01.fluidstream.net:8240/
04-27 19:54:36.005    6204-6728/it.radio I/AACPlayer﹕ Trying to re-connect as 
ICY url icy://wma01.fluidstream.net:8240/
04-27 19:54:36.010    6204-6728/it.radio E/AACPlayer﹕ playAsync():
    java.net.MalformedURLException: Unknown protocol: icy
            at java.net.URL.<init>(URL.java:184)
            at java.net.URL.<init>(URL.java:127)
            at com.spoledge.aacdecoder.AACPlayer.openConnection(AACPlayer.java:548)
            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:328)
            at com.spoledge.aacdecoder.AACPlayer$1.run(AACPlayer.java:296)
            at java.lang.Thread.run(Thread.java:841)
```

Original issue reported on code.google.com by `fabri8bit` on 27 Apr 2014 at 5:56

**Comment by citerio** [comment]
Hey buddies, you have to add this before calling play:

try { 
    java.net.URL.setURLStreamHandlerFactory( new java.net.URLStreamHandlerFactory(){ public java.net.URLStreamHandler createURLStreamHandler( String protocol ) { Log.d( LOG, "Asking for stream handler for protocol: '" + protocol + "'" ); if ("icy".equals( protocol )) return new com.spoledge.aacdecoder.IcyURLStreamHandler(); return null; } }); 
    } catch (Throwable t) { Log.w( LOG, "Cannot set the ICY URLStreamHandler - maybe already set ? - " + t ); }
