### ISSUE TITLE
com.spoledge.aacdecoder.PCMFeed.run(PCMFeed.java:420)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vbartacek/aacdecoder-android#66]
```
What steps will reproduce the problem?
1.I don't know


java.lang.NullPointerException
at com.spoledge.aacdecoder.PCMFeed.run(PCMFeed.java:420)
at java.lang.Thread.run(Thread.java:856)

I have this error on some occasions and on different devices

```

Original issue reported on code.google.com by `Akir...@gmail.com` on 9 Sep 2014 at 4:19

**Comment by 089apps** [comment]
same here, atrack nullcheck is missing
atrack.flush(); 
perhaps we should add "return;" within the catch (line 363)?
