### ISSUE TITLE
Fatal issue

### ISSUE THREAD

**Issue by ferenczAndras** [vbartacek/aacdecoder-android#80]
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.ferenczandras.marosvasarhelyiradio-2/lib/arm/libaacdecoder.so: has text relocations
       at java.lang.Runtime.loadLibrary(Runtime.java:372)
       at java.lang.System.loadLibrary(System.java:1076)
       at com.spoledge.aacdecoder.Decoder.loadLibrary(Decoder.java:187)
       at com.spoledge.aacdecoder.Decoder.create(Decoder.java:221)
       at com.spoledge.aacdecoder.Decoder.create(Decoder.java:198)
       at com.spoledge.aacdecoder.AACPlayer.createDecoder(AACPlayer.java:508)
       at com.spoledge.aacdecoder.MultiPlayer.createDecoder(MultiPlayer.java:91)
       at com.spoledge.aacdecoder.AACPlayer.<init>(AACPlayer.java:130)
       at com.spoledge.aacdecoder.MultiPlayer.<init>(MultiPlayer.java:81)
       at co.mobiwise.library.radio.RadioPlayerService.getPlayer(RadioPlayerService.java:401)
       at co.mobiwise.library.radio.RadioPlayerService.onCreate(RadioPlayerService.java:228)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2895)
       at android.app.ActivityThread.access$1900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5527)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

I have no idea what happened ...

**Comment by Informatheus** [comment]
@ferenczAndras use it on your project.
https://mega.nz/#!EQIVTLIL!mwwakCztR5yd_VjAjS7TJ0kCKO3hrH5mqFkcth9SLc0

**Comment by mpccolorado** [comment]
@Informatheus were you able to also generate the 64 version files?

Thanks!!

**Comment by Informatheus** [comment]
Which files? 

Date: Mon, 25 Apr 2016 09:49:37 -0700

**Comment by mpccolorado** [comment]
Sorry for the delay @Informatheus, I mean these ones: #74 

Thanks!

**Comment by ghost** [comment]
@Informatheus how to use your given files on project to solve this issue

**Comment by willsazon** [comment]
Using the attached file, aim for the error java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/myapp-1/lib/arm/libaacdecoder.so: has text relocations in Android M using the Moto G device. On other devices like J7 among others the problem does not exist. Has anyone managed to resolve this issue?
